const FAMILY_DATA = [
  { id: "root", name: "NACHROWI\n& DEWI MARIAM", parentId: "", level: 0,photo: "images/Nachrowi.jpg" },
  { id: "node_1", name: "MUTMA'INAH\n& NUR HASAN", parentId: "root", level: 1 },
  { id: "node_2", name: "KHOSIM MUSTOFA\n& MUNJIYAH", parentId: "root", level: 1 },
  { id: "node_3", name: "Qosidah\n& Bastomi (Alm)", parentId: "node_2", level: 2 },
  { id: "node_4", name: "Vivin", parentId: "node_3", level: 3 },
  { id: "node_5", name: "Unknown", parentId: "node_3", level: 3 },
  { id: "node_6", name: "Unknown", parentId: "node_3", level: 3 },
  { id: "node_7", name: "Kholifah\n& Nur Fadil", parentId: "node_2", level: 2 },
  { id: "node_8", name: "Ika", parentId: "node_7", level: 3 },
  { id: "node_9", name: "Unknown", parentId: "node_7", level: 3 },
  { id: "node_10", name: "Khoirul Anwar\n& Hartatik", parentId: "node_2", level: 2 },
  { id: "node_11", name: "Hardi", parentId: "node_10", level: 3 },
  { id: "node_12", name: "Unknown", parentId: "node_10", level: 3 },
  { id: "node_13", name: "Kun Faizah\n& M. Suqi Manan", parentId: "node_2", level: 2 },
  { id: "node_14", name: "Zainudin Hanif", parentId: "node_13", level: 3 },
  { id: "node_15", name: "Linda Hanafiah", parentId: "node_13", level: 3 },
  { id: "node_16", name: "Kamilah\n& Suwandi", parentId: "node_2", level: 2 },
  { id: "node_17", name: "Unknown", parentId: "node_16", level: 3 },
  { id: "node_18", name: "Unknown", parentId: "node_16", level: 3 },
  { id: "node_19", name: "Kholid Mustofa\n& Unknown", parentId: "node_2", level: 2 },
  { id: "node_20", name: "Unknown", parentId: "node_19", level: 3 },
  { id: "node_21", name: "Jadid Mustofa\n& Nur Aini", parentId: "node_2", level: 2 },
  { id: "node_22", name: "Unknown", parentId: "node_21", level: 3 },
  { id: "node_23", name: "Unknown", parentId: "node_21", level: 3 },
  { id: "node_24", name: "Jawad Mustofa\n& Nur Azizah", parentId: "node_2", level: 2 },
  { id: "node_25", name: "Unknown", parentId: "node_24", level: 3 },
  { id: "node_26", name: "Unknown", parentId: "node_24", level: 3 },
  { id: "node_27", name: "MARDIYAH\n& M. MUZAIYEN BAKRI", parentId: "root", level: 1 },
  { id: "node_28", name: "Dzakwan Ambara\n& Nur Aini", parentId: "node_27", level: 2 },
  { id: "node_29", name: "Unknown", parentId: "node_28", level: 3 },
  { id: "node_30", name: "Unknown", parentId: "node_28", level: 3 },
  { id: "node_31", name: "Unknown", parentId: "node_28", level: 3 },
  { id: "node_32", name: "Unknown", parentId: "node_28", level: 3 },
  { id: "node_33", name: "Muthohharul Jannan\n& Neng Ati-ati", parentId: "node_27", level: 2 },
  { id: "node_34", name: "Unknown", parentId: "node_33", level: 3 },
  { id: "node_35", name: "Unknown", parentId: "node_33", level: 3 },
  { id: "node_36", name: "Ulumiyah\n& Nafiq Ridwan", parentId: "node_27", level: 2 },
  { id: "node_37", name: "Ninis", parentId: "node_36", level: 3 },
  { id: "node_38", name: "Unknown", parentId: "node_37", level: 4 },
  { id: "node_39", name: "Unknown", parentId: "node_37", level: 4 },
  { id: "node_40", name: "Wildana Widad Fitriana", parentId: "node_36", level: 3 },
  { id: "node_41", name: "Marsha Laila", parentId: "node_36", level: 3 },
  { id: "node_42", name: "Chamidah Hanum\n& Eriwanto", parentId: "node_27", level: 2 },
  { id: "node_43", name: "Riris", parentId: "node_42", level: 3 },
  { id: "node_44", name: "Dawas", parentId: "node_42", level: 3 },
  { id: "node_45", name: "Luluk Jamilah\n& Unknown", parentId: "node_27", level: 2 },
  { id: "node_46", name: "Unknown", parentId: "node_45", level: 3 },
  { id: "node_47", name: "Unknown", parentId: "node_45", level: 3 },
  { id: "node_48", name: "MOETASLIMAH\n& SHOELCHAN", parentId: "root", level: 1, photo:"images/Soelchan.jpeg" },
  { id: "node_49", name: "Nadhiroh\n& Ahmad Maimun", parentId: "node_48", level: 2 },
  { id: "node_50", name: "Niswatul Mustafidah\n& Ali Budiarto", parentId: "node_49", level: 3 },
  { id: "node_51", name: "Luna", parentId: "node_50", level: 4 },
  { id: "node_52", name: "Ahmad Zidny Yusron\n& Unknown", parentId: "node_49", level: 3 },
  { id: "node_53", name: "Unknown", parentId: "node_52", level: 4 },
  { id: "node_54", name: "Unknown", parentId: "node_52", level: 4 },
  { id: "node_55", name: "Unknown", parentId: "node_52", level: 4 },
  { id: "node_56", name: "M. Ismet Amrillah\n& Jihan", parentId: "node_49", level: 3 },
  { id: "node_57", name: "Ghisna", parentId: "node_56", level: 4 },
  { id: "node_128", name: "M.Taufik\n(alm)", parentId: "node_48", level: 2 },
  { id: "node_129", name: "Ahmad Mustafid\n(alm)", parentId: "node_48", level: 2 },
  { id: "node_58", name: "Aunur Rofik\n& Amik Suparwati Nengseh", parentId: "node_48", level: 2 },
  { id: "node_59", name: "Amelia Syuafitri\n& Akhmal Musafa", parentId: "node_58", level: 3 },
  { id: "node_60", name: "Rekemal Ramadhan Alfarabi", parentId: "node_59", level: 4 },
  { id: "node_61", name: "Kemal Farzan Arfarizi", parentId: "node_59", level: 4 },
  { id: "node_62", name: "Dias Deva Ardani \n& Sri Wahyuni", parentId: "node_58", level: 3},
  { id: "node_63", name: "Alenna Zahra", parentId: "node_62", level: 4 },
  { id: "node_64", name: "Atta", parentId: "node_62", level: 4 },
  { id: "node_65", name: "Faisal Charis\n&Fauzia Novi", parentId: "node_58", level: 3 },
  { id: "node_66", name: "Ahmad Elvin Ivaldi\n& Salsabillah", parentId: "node_58", level: 3 },
  { id: "node_67", name: "Yusuf", parentId: "node_66", level: 4 },
  { id: "node_68", name: "Alfi Asyadda Tasbieta", parentId: "node_58", level: 3 },
  { id: "node_69", name: "Mas'Udi\n& Lilis Nurhayati", parentId: "node_48", level: 2, photo: "images/Masud.jpeg"},
  { id: "node_70", name: "Ahmad Fakhrurrozi\n& Nursiva Fitriani", parentId: "node_69", level: 3, photo: "images/Ozzy.jpeg" },
  { id: "node_71", name: "Mikail Fawwaz Ruziva", parentId: "node_70", level: 4 ,  photo: "images/Mikail Fawwaz Ruziva.jpeg"},
  { id: "node_72", name: "Ailsa Nabilah\n& Cakra Birahmadhika", parentId: "node_69", level: 3, photo: "images/Cakra Birahmadika.png"},
  { id: "node_73", name: "Kianara Anindya\nPutri Birahmadhika", parentId: "node_72", level: 4, photo: "images/Kianara.jpeg"},
  { id: "node_74", name: "Alwan Hakim Ramadhani", parentId: "node_69", level: 3,  photo: "images/alwan hakim ramadhani.jpeg" },
  { id: "node_75", name: "Ahmad Rif'an\n& Umi Rahayu", parentId: "node_48", level: 2 },
  { id: "node_76", name: "Nadia Ariesta Azzarin", parentId: "node_75", level: 3 },
  { id: "node_77", name: "Nadinda Itsna Suhaela", parentId: "node_75", level: 3, photo:"images/Nadinda Itsna Suhaela.png"},
  { id: "node_78", name: "Nurul Muttaqin\n& Siti Isngadah", parentId: "node_48", level: 2 },
  { id: "node_79", name: "Adi Rizky Hasan\n& Prillya Hutaning Tias", parentId: "node_78", level: 3 },
  { id: "node_80", name: "Rachel", parentId: "node_79", level: 4 },
  { id: "node_81", name: "Fahri Arkana", parentId: "node_79", level: 4 },
  { id: "node_82", name: "Rizal Maula Fitroni", parentId: "node_78", level: 3 },
  { id: "node_130", name: "Umma Khasuna\n(alm)", parentId: "node_48", level: 2 },
  { id: "node_83", name: "Awam Abdullah\n& Ipung Purwati", parentId: "node_48", level: 2 },
  { id: "node_84", name: "Avadata Firdausin", parentId: "node_83", level: 3 },
  { id: "node_85", name: "Gibron Khoiruzade Attaqi", parentId: "node_83", level: 3 },
  { id: "node_86", name: "Hidayati Rohmatun\n& Dwi Febriyanto", parentId: "node_48", level: 2 },
  { id: "node_87", name: "M. Wildan Aufar Ilman", parentId: "node_86", level: 3 },
  { id: "node_88", name: "M. Nailul Yusril Al Ghifari", parentId: "node_86", level: 3 },
  { id: "node_89", name: "Maida Alimatunisa", parentId: "node_86", level: 3, photo:"images/Maidah.jpeg" },
  { id: "node_90", name: "NUR JANNAH\n& NUR KASAN MANAN", parentId: "root", level: 1 },
  { id: "node_91", name: "Lailatul Latifah\n& Mardi", parentId: "node_90", level: 2 },
  { id: "node_92", name: "Haqqi Annazil", parentId: "node_91", level: 3 },
  { id: "node_93", name: "Rizky", parentId: "node_91", level: 3 },
  { id: "node_94", name: "Iffa Maulidia (Alm.)\n& Yurid", parentId: "node_90", level: 2 },
  { id: "node_95", name: "Shella", parentId: "node_94", level: 3 },
  { id: "node_96", name: "Unknown", parentId: "node_94", level: 3 },
  { id: "node_97", name: "Rahmad Aminudin\n& Yuli (Alm)", parentId: "node_90", level: 2 },
  { id: "node_98", name: "Kafi", parentId: "node_97", level: 3 },
  { id: "node_99", name: "Unknown", parentId: "node_97", level: 3 },
  { id: "node_100", name: "Sholehudin\n& Unknown", parentId: "node_90", level: 2 },
  { id: "node_101", name: "Unknown", parentId: "node_100", level: 3 },
  { id: "node_102", name: "Unknown", parentId: "node_100", level: 3 },
  { id: "node_103", name: "Alwin\n& Sari", parentId: "node_90", level: 2 },
  { id: "node_104", name: "Unknown", parentId: "node_103", level: 3 },
  { id: "node_105", name: "NUR FADILAH\n& M. MUKIM ASAD", parentId: "root", level: 1 },
  { id: "node_106", name: "Maqomatul Ithoah\n& Nano Artono", parentId: "node_105", level: 2 },
  { id: "node_107", name: "Hakam", parentId: "node_106", level: 3 },
  { id: "node_108", name: "Unknown", parentId: "node_106", level: 3 },
  { id: "node_109", name: "M. Makki Nuruddin\n& Emma", parentId: "node_105", level: 2 },
  { id: "node_110", name: "Unknown", parentId: "node_109", level: 3 },
  { id: "node_111", name: "Unknown", parentId: "node_109", level: 3 },
  { id: "node_112", name: "Qoulul Jadidah\n& Abdul Rochim", parentId: "node_105", level: 2 },
  { id: "node_113", name: "Qolbi", parentId: "node_112", level: 3 },
  { id: "node_114", name: "Salsabila", parentId: "node_112", level: 3 },
  { id: "node_115", name: "Annas", parentId: "node_105", level: 2 },
  { id: "node_116", name: "MAHMUDAH\n& KHUSAIN ROFI'I", parentId: "root", level: 1 },
  { id: "node_117", name: "Khoiro Umma\n& Ahmad Heriyanto", parentId: "node_116", level: 2 },
  { id: "node_118", name: "Unknown", parentId: "node_117", level: 3 },
  { id: "node_119", name: "Khoirul Anam\n& Didin", parentId: "node_116", level: 2 },
  { id: "node_120", name: "Unknown", parentId: "node_119", level: 3 },
  { id: "node_121", name: "Unknown", parentId: "node_119", level: 3 },
  { id: "node_122", name: "Lukmanul Hakim (Alm)\n& Devi", parentId: "node_116", level: 2 },
  { id: "node_123", name: "Unknown", parentId: "node_122", level: 3 },
  { id: "node_124", name: "Unknown", parentId: "node_122", level: 3 },
  { id: "node_125", name: "Husni (Alm)\n& Unknown", parentId: "node_116", level: 2 },
  { id: "node_126", name: "Unknown", parentId: "node_125", level: 3 },
  { id: "node_127", name: "Ghoni", parentId: "node_116", level: 2 }
];
